In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv("country_vaccination_stats.csv")

In [76]:
df

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [77]:
df["country"].unique()

array(['Argentina', 'Austria', 'Bahrain', 'Belgium', 'Brazil', 'Bulgaria',
       'Canada', 'Chile', 'China', 'Costa Rica', 'Croatia', 'Cyprus',
       'Czechia', 'Denmark', 'Ecuador', 'England', 'Estonia', 'Finland',
       'France', 'Germany', 'Gibraltar', 'Greece', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Ireland', 'Isle of Man', 'Israel', 'Italy',
       'Kuwait', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Mexico',
       'Netherlands', 'Northern Ireland', 'Norway', 'Oman', 'Panama',
       'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey',
       'United Arab Emirates', 'United Kingdom', 'United States', 'Wales'],
      dtype=object)

In [78]:
df.isnull().any()

country               False
date                  False
daily_vaccinations     True
vaccines              False
dtype: bool

In [79]:
df1 = df[df.isna().any(axis=1)]

In [80]:
df1

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
28,Austria,1/5/2021,NaN,Pfizer/BioNTech
48,Bahrain,12/23/2020,NaN,"Pfizer/BioNTech, Sinopharm"
77,Belgium,12/28/2020,NaN,Pfizer/BioNTech
103,Brazil,1/16/2021,NaN,Sinovac
113,Bulgaria,12/29/2020,NaN,"Moderna, Pfizer/BioNTech"
141,Canada,12/14/2020,NaN,"Moderna, Pfizer/BioNTech"
184,Chile,12/24/2020,NaN,Pfizer/BioNTech
217,China,12/15/2020,NaN,"CNBG, Sinovac"
254,Costa Rica,12/24/2020,NaN,Pfizer/BioNTech
280,Croatia,12/30/2020,NaN,Pfizer/BioNTech
307,Cyprus,1/6/2021,NaN,Pfizer/BioNTech
324,Czechia,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
354,Denmark,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
384,Ecuador,1/21/2021,NaN,Pfizer/BioNTech
386,England,12/20/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
422,Estonia,12/28/2020,NaN,Pfizer/BioNTech
451,Finland,12/31/2020,NaN,Pfizer/BioNTech
477,France,1/4/2021,NaN,Pfizer/BioNTech
499,Germany,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
528,Gibraltar,1/10/2021,NaN,Pfizer/BioNTech
543,Greece,12/28/2020,NaN,Pfizer/BioNTech
572,Hungary,12/28/2020,NaN,Pfizer/BioNTech
600,Iceland,12/30/2020,NaN,"Moderna, Pfizer/BioNTech"
627,India,1/15/2021,NaN,"Covaxin, Covishield"
638,Indonesia,1/12/2021,NaN,Sinovac
652,Ireland,12/31/2020,NaN,Pfizer/BioNTech
677,Isle of Man,1/21/2021,NaN,Pfizer/BioNTech
682,Israel,12/19/2020,NaN,"Moderna, Pfizer/BioNTech"
720,Italy,12/27/2020,NaN,Pfizer/BioNTech
750,Kuwait,12/28/2020,NaN,Pfizer/BioNTech
751,Latvia,12/28/2020,NaN,Pfizer/BioNTech
780,Lithuania,12/25/2020,NaN,"Moderna, Pfizer/BioNTech"
812,Luxembourg,12/30/2020,NaN,Pfizer/BioNTech
838,Malta,12/28/2020,NaN,Pfizer/BioNTech
866,Mexico,12/24/2020,NaN,Pfizer/BioNTech
899,Netherlands,1/6/2021,NaN,"Moderna, Pfizer/BioNTech"
916,Northern Ireland,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
959,Norway,12/27/2020,NaN,Pfizer/BioNTech
988,Oman,12/28/2020,NaN,Pfizer/BioNTech
1016,Panama,1/19/2021,NaN,Pfizer/BioNTech
1022,Poland,12/28/2020,NaN,Pfizer/BioNTech
1050,Portugal,12/27/2020,NaN,Pfizer/BioNTech
1079,Romania,12/28/2020,NaN,Pfizer/BioNTech
1108,Russia,12/15/2020,NaN,Sputnik V
1138,Saudi Arabia,1/6/2021,NaN,Pfizer/BioNTech
1150,Scotland,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
1193,Serbia,1/8/2021,NaN,"Pfizer/BioNTech, Sinopharm, Sputnik V"
1211,Seychelles,1/9/2021,NaN,Sinopharm
1226,Singapore,1/11/2021,NaN,Pfizer/BioNTech
1238,Slovakia,1/4/2021,NaN,Pfizer/BioNTech
1256,Slovenia,1/3/2021,NaN,Pfizer/BioNTech
1278,Spain,1/4/2021,NaN,"Moderna, Pfizer/BioNTech"
1300,Sweden,12/27/2020,NaN,Pfizer/BioNTech
1322,Switzerland,12/23/2020,NaN,Pfizer/BioNTech
1352,Turkey,1/13/2021,NaN,Sinovac
1365,United Arab Emirates,1/5/2021,NaN,"Pfizer/BioNTech, Sinopharm"
1386,United Kingdom,12/20/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
1422,United States,12/20/2020,NaN,"Moderna, Pfizer/BioNTech"
1459,Wales,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"

# 4 & 5:
### Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.

In [82]:
df["daily_vaccinations"] = df.apply(
    lambda row: df[df["country"] == row["country"]]["daily_vaccinations"].min() if np.isnan(row["daily_vaccinations"]) else row["daily_vaccinations"],
    axis=1
)

In [83]:
df[df["country"] == "Argentina"]["daily_vaccinations"].min()

6483.0

In [86]:
df

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,6483.0,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [87]:
df.isnull().any()

country               False
date                  False
daily_vaccinations     True
vaccines              False
dtype: bool

In [88]:
df1 = df[df.isna().any(axis=1)]

In [89]:
df1

    country        date  daily_vaccinations         vaccines
750  Kuwait  12/28/2020                 NaN  Pfizer/BioNTech

In [95]:
df["daily_vaccinations"].dtype

dtype('float64')

In [90]:
df[df["country"] == "Kuwait"]

    country        date  daily_vaccinations         vaccines
750  Kuwait  12/28/2020                 NaN  Pfizer/BioNTech

In [98]:
df = df.fillna(0)

In [99]:
df1 = df[df.isna().any(axis=1)]

# 6:
### Code Implementation Task: Implement code to list the top-3 countries with highest median daily vaccination numbers by considering missing values imputed version of dataset.

In [109]:
df_median = df.groupby("country").agg({"daily_vaccinations": "median"}).sort_values(by="daily_vaccinations",ascending=False)

In [110]:
df_median

                      daily_vaccinations
country
United States                   378253.0
China                           276786.0
India                           173922.0
Turkey                          150356.0
United Kingdom                  120409.0
England                         107310.5
Israel                           92587.0
United Arab Emirates             86430.0
Spain                            55238.0
Germany                          51184.0
Italy                            44475.5
France                           41496.0
Russia                           23563.0
Poland                           22702.5
Brazil                           17220.0
Saudi Arabia                     16807.5
Indonesia                        13200.0
Romania                          13030.0
Argentina                        11645.0
Canada                           11044.0
Austria                           7850.0
Denmark                           7095.5
Netherlands                       6762.0
Ireland                           6528.0
Portugal                          5944.0
Scotland                          5821.0
Mexico                            5488.0
Hungary                           5464.5
Sweden                            5382.5
Czechia                           5378.0
Slovakia                          5357.0
Greece                            5290.0
Singapore                         4907.0
Bahrain                           3662.0
Belgium                           3606.0
Switzerland                       3000.0
Norway                            2958.0
Serbia                            2920.0
Croatia                           2485.0
Slovenia                          2374.0
Wales                             2198.0
Northern Ireland                  2135.0
Finland                           2035.5
Lithuania                         1933.5
Panama                            1324.0
Chile                             1291.0
Oman                              1192.0
Estonia                           1043.0
Bulgaria                          1010.0
Seychelles                        1000.0
Gibraltar                          713.0
Cyprus                             708.0
Costa Rica                         675.5
Latvia                             592.0
Malta                              407.5
Isle of Man                        138.0
Ecuador                            108.0
Luxembourg                          88.0
Iceland                             63.0
Kuwait                               0.0

In [111]:
df_median.head(3)

               daily_vaccinations
country
United States            378253.0
China                    276786.0
India                    173922.0

# 7:
### What is the number of total vaccinations done on 1/6/2021 (MM/DD/YYYY) by considering missing values imputed version of dataset? Please  just provide the number as answer.

In [113]:
df_old = df = pd.read_csv("country_vaccination_stats.csv")
df_old

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [116]:
df_old["date"].dtype

dtype('O')

In [120]:
df_date = df_old[df_old["date"] == "1/6/2021"]
df_date

,country,date,daily_vaccinations,vaccines
8,Argentina,1/6/2021,8173.0,Sputnik V
29,Austria,1/6/2021,3368.0,Pfizer/BioNTech
62,Bahrain,1/6/2021,1594.0,"Pfizer/BioNTech, Sinopharm"
86,Belgium,1/6/2021,736.0,Pfizer/BioNTech
121,Bulgaria,1/6/2021,472.0,"Moderna, Pfizer/BioNTech"
164,Canada,1/6/2021,14887.0,"Moderna, Pfizer/BioNTech"
197,Chile,1/6/2021,272.0,Pfizer/BioNTech
239,China,1/6/2021,455357.0,"CNBG, Sinovac"
267,Costa Rica,1/6/2021,763.0,Pfizer/BioNTech
287,Croatia,1/6/2021,1334.0,Pfizer/BioNTech
307,Cyprus,1/6/2021,NaN,Pfizer/BioNTech
334,Czechia,1/6/2021,2439.0,"Moderna, Pfizer/BioNTech"
364,Denmark,1/6/2021,8525.0,"Moderna, Pfizer/BioNTech"
403,England,1/6/2021,98984.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
431,Estonia,1/6/2021,589.0,Pfizer/BioNTech
457,Finland,1/6/2021,839.0,Pfizer/BioNTech
479,France,1/6/2021,8500.0,Pfizer/BioNTech
509,Germany,1/6/2021,42015.0,"Moderna, Pfizer/BioNTech"
552,Greece,1/6/2021,2680.0,Pfizer/BioNTech
581,Hungary,1/6/2021,3959.0,Pfizer/BioNTech
607,Iceland,1/6/2021,63.0,"Moderna, Pfizer/BioNTech"
658,Ireland,1/6/2021,1624.0,Pfizer/BioNTech
700,Israel,1/6/2021,114634.0,"Moderna, Pfizer/BioNTech"
730,Italy,1/6/2021,45417.0,Pfizer/BioNTech
760,Latvia,1/6/2021,338.0,Pfizer/BioNTech
792,Lithuania,1/6/2021,592.0,"Moderna, Pfizer/BioNTech"
819,Luxembourg,1/6/2021,62.0,Pfizer/BioNTech
847,Malta,1/6/2021,304.0,Pfizer/BioNTech
879,Mexico,1/6/2021,4027.0,Pfizer/BioNTech
899,Netherlands,1/6/2021,NaN,"Moderna, Pfizer/BioNTech"
940,Northern Ireland,1/6/2021,3954.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
969,Norway,1/6/2021,1772.0,Pfizer/BioNTech
997,Oman,1/6/2021,1280.0,Pfizer/BioNTech
1031,Poland,1/6/2021,17723.0,Pfizer/BioNTech
1060,Portugal,1/6/2021,4416.0,Pfizer/BioNTech
1088,Romania,1/6/2021,7555.0,Pfizer/BioNTech
1130,Russia,1/6/2021,39532.0,Sputnik V
1138,Saudi Arabia,1/6/2021,NaN,Pfizer/BioNTech
1174,Scotland,1/6/2021,4858.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1240,Slovakia,1/6/2021,3309.0,Pfizer/BioNTech
1259,Slovenia,1/6/2021,2110.0,Pfizer/BioNTech
1280,Spain,1/6/2021,45248.0,"Moderna, Pfizer/BioNTech"
1310,Sweden,1/6/2021,5165.0,Pfizer/BioNTech
1336,Switzerland,1/6/2021,3000.0,Pfizer/BioNTech
1366,United Arab Emirates,1/6/2021,30698.0,"Pfizer/BioNTech, Sinopharm"
1403,United Kingdom,1/6/2021,111155.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1439,United States,1/6/2021,358887.0,"Moderna, Pfizer/BioNTech"
1483,Wales,1/6/2021,3359.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [123]:
df_date["daily_vaccinations"].sum()

1466568.0